[tool.poetry]
name = "pythondjangocraigslistscraper"
version = "0.1.0"
description = ""
authors = ["Karen Thomas <68983668+thomasknashville@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.5"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
